x-api: &api
  image: jotapemattos/rinha-de-backend-2026:v8
  restart: always
  volumes:
    - socks:/socks

  deploy:
    resources:
      limits:
        cpus: "0.45"
        memory: "165MB"

services:
  api1:
    <<: *api
    environment:
      FAST_NPROBE: 16
      FULL_NPROBE: 64
      UDS_PATH: /socks/api1.sock
    healthcheck:
      test: ["CMD-SHELL", "test -S /socks/api1.sock"]
      interval: 2s
      timeout: 1s
      start_period: 5s
      retries: 15

  api2:
    <<: *api
    environment:
      FAST_NPROBE: 16
      FULL_NPROBE: 64
      UDS_PATH: /socks/api2.sock
    healthcheck:
      test: ["CMD-SHELL", "test -S /socks/api2.sock"]
      interval: 2s
      timeout: 1s
      start_period: 5s
      retries: 15

  lb:
    image: jotapemattos/rinha-de-backend-2026-lb:v1
    restart: always
    volumes:
      - socks:/socks
    ports:
      - "9999:9999"
    depends_on:
      api1:
        condition: service_healthy
      api2:
        condition: service_healthy
  
    deploy:
      resources:
        limits:
          cpus: "0.10"
          memory: "20MB"

volumes:
  socks:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: "size=4m,mode=0777"
